window:
    opacity: 0.80

font:
    normal:
        family: "JetBrainsMono NF"
        style: Regular

    bold:
        family: "JetBrainsMono NF"
        style: Bold

    italic:
        family: "JetBrainsMono NF"
        style: Italic

    size: 9.0

