require("my.plugin_config.tokyonight")
require("my.plugin_config.lualine")
require("my.plugin_config.nvim-tree")
require("my.plugin_config.nvim-treesitter")
require("my.plugin_config.telescope")
require("my.plugin_config.nvim-cmp")
require("my.plugin_config.mason")
